#ifdef FSCK

static const char *DefaultLanguageStringTable[SYS_UI_MSG_COUNT] = {
    "No HardDisk Drive (HDD) unit was detected.",
    "The HardDisk Drive (HDD) unit is not formatted.",
    "Please wait...",
    "There was a problem accessing the disk.\nThe operation cannot be completed.",
    "Disk scan completed.",
    "The disk has corrupted data and must be checked.\nCorrupted data will be deleted."};

static const char *DefaultLanguageLabelStringTable[SYS_UI_LBL_COUNT] = {
    "OK",
    "Cancel",
    "Yes",
    "No",
    "Next",
    "Back",
    "Enabled",
    "Disabled",
    "Toggle option",
    "Select field",
    "Abort",
    "Warning",
    "Error",
    "Information",
    "Confirmation",
    "Please wait",
    "Scan Results",
    "Errors found:",
    "Errors fixed:",
    "Some errors could not be fixed."};

#else

static const char *DefaultLanguageStringTable[SYS_UI_MSG_COUNT] = {
    "No HardDisk Drive (HDD) unit was detected.",
    "The HardDisk Drive (HDD) unit is not formatted. Format?\nWarning: All data will be erased.",
    "Failed to format the HardDisk Drive (HDD) unit.",
    "Quit program?",
    "Please wait...",
    "There was a problem accessing the disk.\nThe operation cannot be completed.",
    "Check the disk for problems",
    "Optimize the disk.\nAvailable space may be increased.",
    "Perform a surface scan on the disk",
    "Write zeros to every sector on the disk.",
    "Quit program.",
    "The bad sector could not be remapped.",
    "Bad sector found at LBA %lu.\n\nThe file stored within the remapped sectors will be lost.\n\nSelect action:",
    "An unexpected I/O error has occurred.",
    "Proceed with scanning the disk?\nCorrupted data will be deleted.",
    "Disk scan completed.",
    "Abort scan operation?",
    "Proceed with optimizing the disk?",
    "Disk optimization completed.",
    "Abort optimization?",
    "Proceed with the surface scan?",
    "Disk surface scan completed.",
    "Abort surface scan operation?",
    "Proceed with zero-filling the disk?",
    "Disk zero-filled successfully.",
    "Abort zero-fill operation?",
    "Press START+SELECT to continue.\nPress any other button to abort.",
    "The HardDisk Drive (HDD) unit has a problem.\nPlease run a disk check first.",
    "S.M.A.R.T. has reported that the HardDisk Drive (HDD) unit has failed.\n\nThe HDD unit must be replaced."};

static const char *DefaultLanguageLabelStringTable[SYS_UI_LBL_COUNT] = {
    "OK",
    "Cancel",
    "PASS",
    "FAIL",
    "Yes",
    "No",
    "Next",
    "Back",
    "Enabled",
    "Disabled",
    "Toggle option",
    "Select field",
    "Quit program",
    "Abort",
    "Warning",
    "Error",
    "Information",
    "Confirmation",
    "Please wait",
    "Scanning disk",
    "Surface scanning disk",
    "Zero-filling disk",
    "Time remaining:",
    "Remap",
    "Skip",
    "Remap all",
    "Skip all",
    "Bad sectors:",
    "ATA unit 0:",
    "Model:",
    "Serial:",
    "Firmware:",
    "SMART status:",
    "Capacity:",
    "Check disk for errors",
    "Optimize disk",
    "Perform surface scan",
    "Zero-fill disk",
    "Optimizing disk (1/2)",
    "Optimizing disk (2/2)",
    "MB",
    "GB",
    "TB",
    "Scan Results",
    "Errors found:",
    "Errors fixed:",
    "Some errors could not be fixed."};

#endif
