#ifdef FSCK

enum SYS_UI_MESSAGES {
    SYS_UI_MSG_NO_HDD = 0,
    SYS_UI_MSG_HDD_NOT_FORMATTED,
    SYS_UI_MSG_PLEASE_WAIT,
    SYS_UI_MSG_HDD_FAULT,
    SYS_UI_MSG_SCAN_DISK_COMPLETED_OK,
    SYS_UI_MSG_AUTO_SCAN_DISK_CFM,

    SYS_UI_MSG_COUNT
};

enum SYS_UI_LABEL_TEXT {
    SYS_UI_LBL_OK = 0,
    SYS_UI_LBL_CANCEL,
    SYS_UI_LBL_YES,
    SYS_UI_LBL_NO,
    SYS_UI_LBL_NEXT,
    SYS_UI_LBL_BACK,
    SYS_UI_LBL_ENABLED,
    SYS_UI_LBL_DISABLED,
    SYS_UI_LBL_TOGGLE_OPTION,
    SYS_UI_LBL_SELECT_FIELD,
    SYS_UI_LBL_ABORT,
    SYS_UI_LBL_WARNING,
    SYS_UI_LBL_ERROR,
    SYS_UI_LBL_INFO,
    SYS_UI_LBL_CONFIRM,
    SYS_UI_LBL_WAIT,
    SYS_UI_LBL_SCAN_RESULTS,
    SYS_UI_LBL_ERRORS_FOUND,
    SYS_UI_LBL_ERRORS_FIXED,
    SYS_UI_LBL_SOME_ERRORS_NOT_FIXED,

    SYS_UI_LBL_COUNT
};

#else

enum SYS_UI_MESSAGES {
    SYS_UI_MSG_NO_HDD = 0,
    SYS_UI_MSG_FORMAT_HDD,
    SYS_UI_MSG_FORMAT_HDD_FAILED,
    SYS_UI_MSG_QUIT,
    SYS_UI_MSG_PLEASE_WAIT,
    SYS_UI_MSG_HDD_FAULT,
    SYS_UI_MSG_DSC_SCAN_DISK,
    SYS_UI_MSG_DSC_OPT_DISK,
    SYS_UI_MSG_DSC_SURF_SCAN_DISK,
    SYS_UI_MSG_DSC_ZERO_FILL_DISK,
    SYS_UI_MSG_DSC_QUIT,
    SYS_UI_MSG_SECTOR_PATCH_FAIL,
    SYS_UI_MSG_BAD_SECTOR_FOUND,
    SYS_UI_MSG_UNEXPECTED_ATA_ERR,
    SYS_UI_MSG_SCAN_DISK_CFM,
    SYS_UI_MSG_SCAN_DISK_COMPLETED_OK,
    SYS_UI_MSG_SCAN_DISK_ABORT_CFM,
    SYS_UI_MSG_OPT_DISK_CFM,
    SYS_UI_MSG_OPT_DISK_COMPLETED_OK,
    SYS_UI_MSG_OPT_DISK_ABORT_CFM,
    SYS_UI_MSG_SURF_SCAN_DISK_CFM,
    SYS_UI_MSG_SURF_SCAN_DISK_COMPLETED_OK,
    SYS_UI_MSG_SURF_SCAN_DISK_ABORT_CFM,
    SYS_UI_MSG_ZERO_FILL_DISK_CFM,
    SYS_UI_MSG_ZERO_FILL_DISK_COMPLETED_OK,
    SYS_UI_MSG_ZERO_FILL_DISK_ABORT_CFM,
    SYS_UI_MSG_ZERO_FILL_DISK_CFM_2,
    SYS_UI_MSG_HDD_CORRUPTED,
    SYS_UI_MSG_HDD_SMART_FAILED,

    SYS_UI_MSG_COUNT
};

enum SYS_UI_LABEL_TEXT {
    SYS_UI_LBL_OK = 0,
    SYS_UI_LBL_CANCEL,
    SYS_UI_LBL_PASS,
    SYS_UI_LBL_FAIL,
    SYS_UI_LBL_YES,
    SYS_UI_LBL_NO,
    SYS_UI_LBL_NEXT,
    SYS_UI_LBL_BACK,
    SYS_UI_LBL_ENABLED,
    SYS_UI_LBL_DISABLED,
    SYS_UI_LBL_TOGGLE_OPTION,
    SYS_UI_LBL_SELECT_FIELD,
    SYS_UI_LBL_QUIT,
    SYS_UI_LBL_ABORT,
    SYS_UI_LBL_WARNING,
    SYS_UI_LBL_ERROR,
    SYS_UI_LBL_INFO,
    SYS_UI_LBL_CONFIRM,
    SYS_UI_LBL_WAIT,
    SYS_UI_LBL_SCANNING_DISK,
    SYS_UI_LBL_SURF_SCANNING_DISK,
    SYS_UI_LBL_ZERO_FILLING_DISK,
    SYS_UI_LBL_ETA,
    SYS_UI_LBL_REMAP,
    SYS_UI_LBL_REMAP_ALL,
    SYS_UI_LBL_SKIP,
    SYS_UI_LBL_SKIP_ALL,
    SYS_UI_LBL_BAD_SECTORS,
    SYS_UI_LBL_ATA_UNIT_0,
    SYS_UI_LBL_MODEL,
    SYS_UI_LBL_SERIAL,
    SYS_UI_LBL_FIRMWARE,
    SYS_UI_LBL_SMART_STATUS,
    SYS_UI_LBL_CAPACITY,
    SYS_UI_LBL_SCAN_DISK,
    SYS_UI_LBL_OPT_DISK,
    SYS_UI_LBL_SURF_SCAN_DISK,
    SYS_UI_LBL_ZERO_FILL_DISK,
    SYS_UI_LBL_OPTIMIZING_DISK_P1,
    SYS_UI_LBL_OPTIMIZING_DISK_P2,
    SYS_UI_LBL_MB,
    SYS_UI_LBL_GB,
    SYS_UI_LBL_TB,
    SYS_UI_LBL_SCAN_RESULTS,
    SYS_UI_LBL_ERRORS_FOUND,
    SYS_UI_LBL_ERRORS_FIXED,
    SYS_UI_LBL_SOME_ERRORS_NOT_FIXED,

    SYS_UI_LBL_COUNT
};

#endif
