enum HDSK_DEVCTL {
    HDSK_DEVCTL_GET_FREE = 0,
    HDSK_DEVCTL_GET_HDD_STAT,
    HDSK_DEVCTL_START,
    HDSK_DEVCTL_WAIT,
    HDSK_DEVCTL_POLL,
    HDSK_DEVCTL_GET_STATUS,
    HDSK_DEVCTL_STOP,
    HDSK_DEVCTL_GET_PROGRESS,
};

struct hdskStat
{
    u32 free;
    u32 total;
};
